---
version: 2

unit_tests: &unit_tests
  - run: apt-get -y update && apt-get -y install git libpng-dev
  - run: docker-php-ext-install gd
  - checkout
  - run: >
      curl -o- 'https://getcomposer.org/installer' |
      php -- --quiet --filename=composer --install-dir=/usr/local/bin
  - run: composer install
  - run: php tests/run.php unit

all_tests: &all_tests
  - checkout
  - run: >
        ID=unknown;
        . /etc/os-release;
        if test "$ID" == 'arch' ;
           then cp /usr/lib/libreadline.so.7.0 /root;
           pacman -Sy --noconfirm php php-gd readline;
           cp /root/libreadline.so.7.0 /usr/lib/;
           ln -s /usr/lib/libreadline.so.7.0 /usr/lib/libreadline.so.7;
           sed -i s/\;extension=gd/extension=gd/ /etc/php/php.ini;
           curl -L --output glib.tar.xz https://archive.archlinux.org/packages/g/glibc/glibc-2.29-4-x86_64.pkg.tar.xz;
           pacman -U --noconfirm glib.tar.xz;
        else
           if test $VERSION_ID -le 8 ;
              then
              PHP_VERSION=5;
           fi;
           sed -i s/wheezy/jessie/g /etc/apt/sources.list;
           apt-get -y update && apt-get -y install php$PHP_VERSION-gd ;
        fi
  - run: composer install
  - run: php tests/run.php unit e2e
  - run: if test "$CODACY_PROJECT_TOKEN" != "" ; then vendor/bin/codacycoverage clover ./coverage.xml ; fi;

jobs:
  php-5.4:
    docker:
      - image: thiagoalessio/php:5.4
    steps:
      - checkout
      - run: sed -i s/wheezy/jessie/g /etc/apt/sources.list
      - run: apt-get -y update&&apt-get -y install php5-gd
      - run: extension=gd.so>>/etc/php5/cli/php.ini
      - run: composer install
      - run: php tests/run.php unit

  php-5.6:
    docker:
      - image: php:5.6
    steps: *unit_tests

  php-7.0:
    docker:
      - image: php:7.0
    steps: *unit_tests

  php-7.1:
    docker:
      - image: php:7.1
    steps: *unit_tests

  php-7.2:
    docker:
      - image: php:7.2
    steps: *unit_tests

  tess-3.02:
    docker:
      - image: thiagoalessio/tesseract:3.02
    steps: *all_tests

  tess-3.03:
    docker:
      - image: thiagoalessio/tesseract:3.03
    steps: *all_tests

  tess-3.04:
    docker:
      - image: thiagoalessio/tesseract:3.04
    steps: *all_tests

  tess-3.05:
    docker:
      - image: thiagoalessio/tesseract:3.05
    steps: *all_tests

  tess-4.00:
    docker:
      - image: thiagoalessio/tesseract:4.00
    steps: *all_tests

php_jobs: &php_jobs
  - php-5.4
  - php-5.6
  - php-7.0
  - php-7.1
  - php-7.2

workflows:
  version: 2
  default:
    jobs:
      - php-5.4
      - php-5.6
      - php-7.0
      - php-7.1
      - php-7.2
      - tess-3.02:
          requires: *php_jobs
      - tess-3.03:
          requires: *php_jobs
      - tess-3.04:
          requires: *php_jobs
      - tess-3.05:
          requires: *php_jobs
      - tess-4.00:
          requires: *php_jobs

notify:
  webhooks:
    - url: https://webhooks.gitter.im/e/2a55ca057ba4a0b16123
